all:
	pdflatex main.tex
	pdflatex main.tex
	pdflatex main.tex
clean:
	rm -rfv ./main.toc
	rm -rfv ./main.nav
	rm -rfv ./main.log
	rm -rfv ./main.aux
	rm -rfv ./main.out
	rm -rfv ./main.snm
clean_pdf:
	rm -rfv ./main.toc
	rm -rfv ./main.pdf
	rm -rfv ./main.nav
	rm -rfv ./main.log
	rm -rfv ./main.aux
	rm -rfv ./main.out
	rm -rfv ./main.snm
